name: Python CI

# Especifica cuándo se debe activar el workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define los jobs a ejecutar
jobs:
  build:
    # Nombre del job
    name: Build and Test
    # Especifica el sistema operativo en el que se ejecutará el job
    runs-on: windows-latest

    # Estrategia para correr pruebas en múltiples versiones de Python
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, 3.10, 3.11]

    # Pasos a ejecutar en el job
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov

    - name: Lint code
      run: |
        pip install flake8
        flake8 .

    - name: Run tests with coverage
      run: |
        pytest --cov=./

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
